settings_segment_separator_right=''
settings_segment_separator_left=''
settings_segment_splitter_left=''
settings_segment_splitter_right=''
settings_segment_separator_right=''
settings_segment_separator_left=''
settings_segment_enable_bg_color=0
settings_path_splitter_disable=1
