language: bash
email: false
before_install:
  - sudo add-apt-repository ppa:duggan/bats
  - sudo apt-get update
  - sudo apt-get install bats -y
script: shellcheck -x sbp.bash src/main.bash && bats -r -T test/
